name = "Lillas Create Pack"
author = "Bayi"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56dc23eda40a7d74522e05300b1999983b9b2ce36ea45e8dabc271813d32eaf9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
