name = "Lillas Create Pack"
author = "Bayi"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "701c58ba45ceaa7ba022e37a8dedf851959ddc189324ab5721ab673120149632"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
