name = "Lilla's Create Pack"
author = "Bayi"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f8ed4b7afc7090a79c3d271b55841c0727520bc929512ba0d9c810e856280c1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
